name: Update Go Modules
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Update main Gomod
        run: |
          cd ${{ github.workspace }}
          go mod tidy

      - name: Update test Gomod
        run: |
          cd ${{ github.workspace }}/test
          go mod tidy

      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.MAINTAINER_APPID }}
          private_key: ${{ secrets.MAINTAINER_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Dependencies
          branch: update-dependencies
          delete-branch: true
          title: 'Update Dependencies'
          draft: false
          body: |
            - Update Go Module Dependecies
          labels: |
            Update

      - name: PR result
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      
